# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: 'Free Trial(86d740a1-5cae-4257-92bb-df1b0d665078)'
    subscriptionId: '86d740a1-5cae-4257-92bb-df1b0d665078'
    action: 'Create Or Update Resource Group'
    resourceGroupName: 'AkhilRG1'
    location: 'North Europe'
    templateLocation: 'Linked artifact'
    csmFile: 'LoadBalancedVirtualMachine.json'
    csmParametersFile: 'LoadBalancedVirtualMachine.parameters.json'
    deploymentMode: 'Incremental'